name: AWS-thing

# Controls when the workflow will run
on:
  push:
    branches:
      - dan-cf
    paths:
      - dan_test.yml
  pull_request:
    branches:
      - dan-cf
    paths:
      - dan_test.yml

permissions:  
  id-token: write
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-aws-code:
    name: Update cloudformation file
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
    
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-deploy-role
          aws-region: eu-west-1 
          role-duration-seconds: 1200

      - name: Update stack
        run: aws cloudformation update-stack --stack-name oldmengrinding --template-body file://$GITHUB_WORKSPACE/dan_test.yml